### ISSUE TITLE
[Summary] Server Release v1.0 TODOs

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph#2011]
### Big Changes (通告)

> Hello everyone in the hugegraph community, we are preparing for the first **Apache Release (V1.0.0)**
>
> This is a **big change**, and all component versions will be unified since then, we sincerely welcome everyone's **participation** and **contribution**, thank you
>
> TODOs will be summarized here, and you can leave a comment or send a msg to claim them if u want

## High Priority (高优先级)
- [x] replace `wget` by `curl` or any better way when build(source code)  [TODO: **move to next release**] #2277
- [x] enhance Dockerfile: use the latest code + publish to apache dockerhub #2015 #840 #2046 
- [x] fix license problems #1632 
- [x] hbase-shade 的 `com` 依赖问题 (3种方式选择) @zyxxoo 
- [x]  Check the licenses of all dependent third-party libraries (80%)
  - [x] Find all the dependent license/NOTICE files (unzip the jar package or go to the source code repository) and copy them to the licenses directory of the toolchains repository (refer to the [link](https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-dist/release-docs))
  - [x]  Check whether the license conflicts with Apache2.0
- [x] binary package inspection, description, signature
- [x] support a string of OLAP algorithms #1984 
- [x] old pr review & merge ---- @javeme @imbajin @zyxxoo @coderzc etc.
- [x] check & fix java11 problem #2020 

## Normal Priority (中优先级)

- [x]  add rat ci #2034 
- [x]  rename `com.baidu` to `org.apache` and adjust the package style #2019  (70%)

## Low Priority (低优先级)
- [ ] clean the code / style (refer [PR](https://github.com/apache/incubator-hugegraph-commons/pull/110/files))
- [x] CVE security check & fix the code/dependencies problem

Note: we need adapt other relative repos
