### ISSUE TITLE
[Feature] integrate pd and store components into hugegraph

### ISSUE THREAD

**Issue by VGalaxies** [apache/incubator-hugegraph#2265]
### Feature Description (功能描述)

# Background

Currently, the architecture of the community version of HugeGraph is still in version 1.0. In the internal version 2.0 of HugeGraph, we have the following design goals:

- Support trillion-scale data storage and tens of thousands of graph storages.
- Support multi-active, high availability, dynamic scalability, and automated operation and maintenance.
- Maximize read and write performance.

Based on these goals, we have designed a distributed architecture that supports graph data partitioning and multiple replicas, and separates storage from computation for flexible scaling.

In version 2.0, in addition to the hugegraph-server, we also introduce two additional components: hugegraph-pd and hugegraph-store

![image](https://github.com/apache/incubator-hugegraph/assets/79143929/e298925a-114d-4eab-9f4d-d5ab91e7522f)

The responsibilities of these two components are as follows:

- hugegraph-pd: pd stands for place driver, which can be simply understood as a meta server responsible for service discovery, partition information storage, and node scheduling.
- hugegraph-store: as a new built-in storage backend, it uses RocksDB as the distributed backend storage foundation.

We will gradually merge the internal version 2.0 of HugeGraph into the community version. Therefore, the first step is to integrate the hugegraph-pd and hugegraph-store modules into this repository.

# Tasks

- [ ] Adjust the project structure of this repository to include three sub-modules: hugegraph-server, hugegraph-pd, hugegraph-store at the root level.
- [ ] Merge the internal version of pd.
- [ ] Merge the internal version of store.
- [ ] Configuration adjustments (including merging dependencies, unifying version numbers, Maven compilation adjustments, etc.).
- [ ] Perform code adaptation tasks (hugegraph-server needs to introduce modules to connect with hugegraph-pd and hugegraph-store, and make adjustments to other modules, etc.).
- [ ] ...

**Comment by Pengzna** [comment]
please add this [sub-task](https://github.com/apache/incubator-hugegraph/issues/2482) to this issue, thx~

**Comment by VGalaxies** [comment]
close by #2575, PD and Store components have been integrated into hugegraph and will continue to evolve in future versions...
