### ISSUE TITLE
[Summary] Enhance code style warnings in server

### ISSUE THREAD

**Issue by msgui** [apache/incubator-hugegraph#2435]
### SubTask

**PS: One PR for multiple modules is fine, but if the total code exceeds **4000** lines, split it into multiple PRs.**

- [x] Adhere to the code conventions outlined in [HugeGraph-Code-Style-Guide](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide) (please refine the hg-style.xml specification @returnToInnocence) https://github.com/apache/incubator-hugegraph/pull/2457
   - [x] Add the option 'BLANK_LINES_AFTER_CLASS_HEADER' 
   - [x] Add the option 'KEEP_BLANK_LINES'
   - [x] ....
- [x] Correct the copyright format.
	- [x] #2438
	- [x] #2445
- [x] Format the server module 
   - [x] hugegraph-api & cassandra & palo & postgresql & rocksdb & scylladb & test & hbase & mysql (wip #2439)
   - [x] hugegraph-core #2440
   - [x] hugegraph-dist & example #2441
   - [x]  remove extra blank lines https://github.com/apache/incubator-hugegraph/pull/2459
- [x] clean up the code. https://github.com/apache/incubator-hugegraph/pull/2456
- [x] Doc [hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg](https://hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg)@returnToInnocence
	- [x] Provide doc on how to retain/install multiple versions of IntelliJ IDE 
	- [x] Unified IDE Rules Setup Tutorial 

### Expected & Actual behavior (期望与实际表现)

![image](https://github.com/apache/incubator-hugegraph/assets/87920097/b57f2eee-d002-482c-a87c-4fb094399425)
![image](https://github.com/apache/incubator-hugegraph/assets/87920097/69833dec-c49a-4567-891d-71e30671bde2)
![image](https://github.com/apache/incubator-hugegraph/assets/87920097/0c42bafd-dba2-4de7-bee3-f425533fb267)

### TODO
- [ ] IDEA formatting plugin currently lacks support for adding a blank line after enum declarations.![image](https://github.com/apache/incubator-hugegraph/assets/87920097/9c624fb0-7170-4036-b0d1-cc4597565ba9)
- [ ] Use [spotless](https://github.com/diffplug/spotless) to format code

**Comment by VGalaxies** [comment]
@msgui consider introducing the specific steps for formatting, cleaning, and correcting in the relevant PRs to help us in **PR validation** :)

**Comment by msgui** [comment]
> consider introducing the specific steps for formatting, cleaning, and correcting in the relevant PRs to help us in **PR validation** :)

1. Configure IDEA based on the [[‌⁤⁢‍‍⁣‌⁤‍⁤⁢‬‍⁤⁢﻿⁤﻿⁡⁡‬‌⁤⁢⁡⁤⁣‍⁣﻿⁤‌⁤⁣⁤项目迁移/改包名 + IDEA 配置说明 (完整版) - 飞书云文档](https://hugegraph.feishu.cn/wiki/C3U3wWOGSi5z3jkTRpIc5nwdnrb)](https://hugegraph.feishu.cn/wiki/C3U3wWOGSi5z3jkTRpIc5nwdnrb).
2. Review whether hugegraph-style.xml aligns with the specifications outlined in the [[HugeGraph Code Style Guide](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide)](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide).

3. Import the latest license header (found at the end of the [[HugeGraph Code Style Guide](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide)](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide)) into IDEA and utilize the "Update Copyright" feature to keep the license header up-to-date.

4. Utilize IDEA plugins such as Reformat and Clean Code for code formatting.

**Comment by returnToInnocence** [comment]
Adhere to the code conventions outlined in [HugeGraph-Code-Style-Guide](https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide) (please refine the hg-style.xml specification @returnToInnocence)https://github.com/apache/incubator-hugegraph/pull/2457

**Comment by returnToInnocence** [comment]
Suddenly a new idea, perhaps as a future thing to do, is to try to migrate the entire contents of the entire `hg-style.xml` file to`.editorconfig`

This is because the.editorconfig file has some other advantages that `hg-style.xml` does not have when I was looking at the documentation for this, such as:
- The`.editorconfig` file can also define coding conventions that cannot be defined by `hg-style.xml`, such as code style, formatting, and naming, which can help improve code consistency and readability.
- The`.editorconfig` file does not require the user to make any additional configuration, such as importing code style. If this file exists in the project, it will be automatically invoked by default, and code sytle will be overwritten

Therefore, I wonder if we should further try to gather the configuration of a function as much as possible in the future, instead of spreading it into multiple Settings, and reduce the user's perception of format as little as possible at one time

Hence the above idea

**Comment by VGalaxies** [comment]
> Suddenly a new idea, perhaps as a future thing to do, is to try to migrate the entire contents of the entire `hg-style.xml` file to`.editorconfig`
> 
> This is because the.editorconfig file has some other advantages that `hg-style.xml` does not have when I was looking at the documentation for this, such as:
> 
> * The`.editorconfig` file can also define coding conventions that cannot be defined by `hg-style.xml`, such as code style, formatting, and naming, which can help improve code consistency and readability.
> * The`.editorconfig` file does not require the user to make any additional configuration, such as importing code style. If this file exists in the project, it will be automatically invoked by default, and code sytle will be overwritten
> 
> Therefore, I wonder if we should further try to gather the configuration of a function as much as possible in the future, instead of spreading it into multiple Settings, and reduce the user's perception of format as little as possible at one time

Indeed, I found that #2457 uses both `hugegraph-style.xml` and `.editorconfig` to control code style. If the control scope of the editorconfig file is broader than the idea code style XML, it might be worth considering consolidating them into `.editorconfig`.

**Comment by returnToInnocence** [comment]
> > Suddenly a new idea, perhaps as a future thing to do, is to try to migrate the entire contents of the entire `hg-style.xml` file to`.editorconfig`
> > This is because the.editorconfig file has some other advantages that `hg-style.xml` does not have when I was looking at the documentation for this, such as:
> > 
> > * The`.editorconfig` file can also define coding conventions that cannot be defined by `hg-style.xml`, such as code style, formatting, and naming, which can help improve code consistency and readability.
> > * The`.editorconfig` file does not require the user to make any additional configuration, such as importing code style. If this file exists in the project, it will be automatically invoked by default, and code sytle will be overwritten
> > 
> > Therefore, I wonder if we should further try to gather the configuration of a function as much as possible in the future, instead of spreading it into multiple Settings, and reduce the user's perception of format as little as possible at one time
> 
> Indeed, I found that #2457 uses both `hugegraph-style.xml` and `.editorconfig` to control code style. If the control scope of the editorconfig file is broader than the idea code style XML, it might be worth considering consolidating them into `.editorconfig`.
> 
> > In the context of IntelliJ IDEA, perhaps this is feasible, see https://www.jetbrains.com/help/idea/editorconfig.html
> > ![image](https://private-user-images.githubusercontent.com/79143929/308034747-a43fc90d-c355-482a-a2e3-0bb1b21fe425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDkzMjIsIm5iZiI6MTcwOTAwOTAyMiwicGF0aCI6Ii83OTE0MzkyOS8zMDgwMzQ3NDctYTQzZmM5MGQtYzM1NS00ODJhLWEyZTMtMGJiMWIyMWZlNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA0NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OGFmNjJjOWNlZjVlMjgwODgzNDEwMjM4MjRkMjE4OTEwMmUxNzk3MWFhNjRlM2ZiYjZiZGM3NDc3MDNjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WpxhtthvVPz3ju4iHNiZVUrys09alvxHY59jS-J4uHU)
> 
> Perhaps it's possible to export the current `hugegraph-style.xml` to `.editorconfig` format and merge it with the existing `.editorconfig` to see if the previously defined styles are compromised...

get it! I will try to export it this afternoon to see how it works!

**Comment by returnToInnocence** [comment]
- [ ] Provide doc on how to retain/install multiple versions of IntelliJ IDE @returnToInnocence  
- [ ] Unified IDE Rules Setup Tutorial @returnToInnocence [IDE Rules Setup Tutorial](https://hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg?from=from_copylink) (wip)

Since the above two tasks are logically coherent, I merged them into one  @msgui 
https://hugegraph.feishu.cn/wiki/NzaxwWIRHi5mJGkXkR0cHx6mnbg
