### ISSUE TITLE
[Featuer] Support build docker image from Dockerfile (Task Summary)

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph#840]
> Apache [HugeGraph](https://hub.docker.com/r/hugegraph/hugegraph) DockerHub: https://hub.docker.com/r/hugegraph/hugegraph

## Usage:
```bash
# 0. download image (latest)
docker pull hugegraph/hugegraph

# 1. start container
docker run -itd hugegraph/hugegraph  # start server in daemon mode

# (Optional configs to expose network port outside)
docker run -itd --name=graph -p 18080:8080 hugegraph/hugegraph

# 2. (Optional) enter the container & start hugegraph-hubble
docker exec -it graph bash
xxx 
```

## Feature Needs
1. Add Dockerfile for running HugeServer
2. Users can pull/run the image from dockerhub directly.

And anyone who has other suggestion for docker image can comment here

_After PR, will update the doc_ 📝 

## Update in 2023.02.22:

Due to the project will move to Apache Foundation, we'll use  `1.0.0` as the server version & bind hubble with it, reopen this issue until it meets the new need, any suggestions for `Dockerfile` are welcome.

- [ ] use [docker-slim](https://github.com/docker-slim/docker-slim) to slim the image
- [ ] keep the tags same with server (like `hugegraph/hugegraph:1.0.0`)
- [ ] use hubble instead of studio to support new features
- [ ] use a script to run server & hubble together  OR use docker-compose to manage them
- [ ] pre-load some data or graphs in container so that users can traverse the graph with one step (docker run)
- [ ] use dockerhub(autobuild), currently it's not free to use (Submit a OSS request) 
- [x] support `ARM` env (for M1 laptop, refer [doc](https://github.com/marketplace/actions/docker-setup-buildx))
- [x] consider better way (like add a option/program to run backward) to avoid modify start-script #2118
- [x] adopt v0.12 (support raft based replication)
- [x] use github actions to publish images
- [x] use jdk11 for runtime #2118
- [x] use `multi-stage` Dockerfile way to slim the image
- [x] support build from the (latest) source code  #2118

Refer:
1. [Reduce the size of container images with DockerSlim](https://developers.redhat.com/articles/2022/01/17/reduce-size-container-images-dockerslim#)
2. [One docker  container with multi process](https://www.cnblogs.com/liwenchao1995/p/16732217.html) (Not graceful:)
3. [How to use dumb-init to replace the pid1 in docker](https://promacanthus.netlify.app/cloud-native/docker/init-system/02-dumb-init%E4%BD%BF%E7%94%A8/)

**Comment by javeme** [comment]
@imbajin Thanks. do we need a repository like this: https://hub.docker.com/repository/docker/hugegraph/hugegraph

**Comment by imbajin** [comment]
> @imbajin Thanks. do we need a repository like this: https://hub.docker.com/repository/docker/hugegraph/hugegraph

Yep, and it should be **associated with** the current github repository, then add `access token`
for dockerhub to auto get the change from **Dockerfile** & autobuild the image

Refer to :
1. [Link to Github](https://docs.docker.com/docker-hub/builds/link-source/)
2. [Autobuild from Dockerhub](https://docs.docker.com/docker-hub/builds/)

**Comment by javeme** [comment]
@imbajin done
![image](https://user-images.githubusercontent.com/9625821/72892340-36d81e80-3d51-11ea-98ec-1d62d2392076.png)

**Comment by T-baby** [comment]
什么时候支持自动发布到 dockerhub

**Comment by imbajin** [comment]
> 什么时候支持自动发布到 dockerhub

如果没有紧急需要的话, 应该是等分布式 rocksdb 版稳定之后一起处理把, 不然要改动的地方还挺多

**Comment by T-baby** [comment]
下版本的 hugegraph 支持分布式是吧。

**Comment by imbajin** [comment]
> 下版本的 hugegraph 支持分布式是吧。

没有特殊情况是哒, 不过就算分布式 rocksdb 没有 12 版发布, 也会重新出一个正式的 docker 镜像(包括 hubble 的)

**Comment by niconical** [comment]
Really meaningful work, I hope I can apply for this project on GLCC 2023!

**Comment by niconical** [comment]
It seems hard to find relevant PRs for `use github actions to publish images`.

**Comment by imbajin** [comment]
> It seems hard to find relevant PRs for `use github actions to publish images`.

due to the permission lack, we have to publish it in an separate repo:
- https://github.com/imbajin/nocode/blob/master/.github/workflows/server-docker.yml
- https://github.com/hugegraph/hugegraph-actions/tree/main/.github/workflows

**Comment by niconical** [comment]
Ref: https://discuss.tvm.apache.org/t/auto-build-and-test-tvm-ci-docker-images-nightly/10347

**Comment by DoodleBears** [comment]
> * [ ]  fix that hubble can't use `localhost/0.0.0.0` & add a script to update the image

What should I do if I user Docker to run hugegraph/hugegraph and hugegraph/hubble and encounter 
```
服务 localhost:8080 不可用
```

**Comment by imbajin** [comment]
> > * [ ]  fix that hubble can't use `localhost/0.0.0.0` & add a script to update the image
> 
> What should I do if I user Docker to run hugegraph/hugegraph and hugegraph/hubble and encounter 
> ```
> 服务 localhost:8080 不可用
> ```

could use the real ip like `10.xx.xx.7` directly

@coderzc ，please assign this bug for your stu~

**Comment by coderzc** [comment]
@aroundabout PTAL.

**Comment by aroundabout** [comment]
here

**Comment by aroundabout** [comment]
> > * [ ]   fix that hubble can't use `localhost/0.0.0.0` & add a script to update the image
> 
> What should I do if I user Docker to run hugegraph/hugegraph and hugegraph/hubble and encounter
> 
> ```
> 服务 localhost:8080 不可用
> ```

Can you provide more information? Like the command you use.

**Comment by imbajin** [comment]
> > > * [ ]    fix that hubble can't use `localhost/0.0.0.0` & add a script to update the image
> > 
> > 
> > What should I do if I user Docker to run hugegraph/hugegraph and hugegraph/hubble and encounter
> > ```
> > 服务 localhost:8080 不可用
> > ```
> 
> Can you provide more information? Like the command you use.

@aroundabout @DoodleBears 
better open a new issue in toolchain to handle it, this issue used for summary, keep it clean (I'll hide them later), thanks~ 🆒

**Comment by DoodleBears** [comment]
opened: 
https://github.com/apache/incubator-hugegraph-toolchain/issues/490#issue-1796657832

**Comment by DoodleBears** [comment]
> > > * [ ]    fix that hubble can't use `localhost/0.0.0.0` & add a script to update the image
> > 
> > 
> > What should I do if I user Docker to run hugegraph/hugegraph and hugegraph/hubble and encounter
> > ```
> > 服务 localhost:8080 不可用
> > ```
> 
> Can you provide more information? Like the command you use.

mentioned here: 
https://github.com/apache/incubator-hugegraph-toolchain/issues/490#issue-1796657832
